### ISSUE TITLE
login problems

### ISSUE THREAD

**Issue by StanceFreak** [philimones-group/hds-explorer-tablet#1]
how can I create a user for login into the app? I've added my server url in the settings and it only work on the synchronize feature not the login one. and then when I'm checking the LoginActivity code, it seems that the app only validates users from the local database not from the hds explorer server users

**Comment by paulphilimone** [comment]
Hi StanceFreak,

The login feature works offline while the Synchronize button works by connecting to the server.
To be able to login offline the mobile device must be synchronized to the server first.

1. The initial step after you configured the server is to export the mobile database.
    Go to webapp page and to the menu **Synchronization Tasks** -> **Mobile Database Export Manager**
    and click **Export All**.
>     Whenever you have updated you server data content (new users, new households, forms, etc) you must Export 
>     Mobile Database.

2. On the mobile device, enter the credentials and tap Synchronize -> Synchronize All
3. Go back to the login panel, enter credentials and click Login.
4. If you want to create new Users, go to the webapp and click the menu **Users** and click **Add User**, at the end dont forget to Export Mobile Database
    
    
Thanks for tryinh the app.

Contact: paulphilimone@gmail.com, for more detailed information and the user manual.
